### ISSUE TITLE
Getting started with SmartDeviceLink-iOS?

### ISSUE THREAD

**Issue by tomhoag** [smartdevicelink/SmartDeviceLink-iOS#119]
Is there a sample project or a getting started doc somewhere?

In lieu of either of those, what is the basic starting point for making the connection with SDL?  I'm assuming that the entry point is instantiating an SDLProxy from the SDLProxyFactory?

I have SDL core running in a Parallels VM on the same Mac I'm doing iOS development on.  The network interface for the VM is set to bridge mode so both devices are sharing 192.168.1.7 but the following

```objective-c
_sdlProxy = [SDLProxyFactory buildSDLProxyWithListener:self tcpIPAddress:@"192.168.1.7" tcpPort:@"8087"];
```
(I picked up the port from the smartDeviceLink.ini) results in a console log message: 

```
2015-03-13 14:53:24.970 SDLPlay[90136:3453271] [TCP] Init
2015-03-13 14:53:24.979 SDLPlay[90136:3453271] [TCP] Server Not Ready, Connection Failed
```

Am I on the right track?  Any pointers appreciated!

**Comment by joeljfischer** [comment]
Hey Tom, we're still working on getting documentation and sample projects etc. up and working. There is a pretty basic one on the `develop` branch at the moment. That code is obviously still in development, so be a bit wary there.

The log that you have there indicates that the device side is incapable of finding a server on the IP and port specified. The default port for SDL Core is `12345`, so double check that, unless you changed the configuration. Also, I'm not sure how bridging the VM to the Mac you're doing (I'm assuming in simulator?) development on would affect things. I pretty much always do my work on device.

**Comment by tomhoag** [comment]
Thanks Joel.  I was able to get the sample project running.  Thanks for the tip on the default port.  I had no issues running the sample project in the simulator with my setup.
