### ISSUE TITLE
Getting a template and populating?

### ISSUE THREAD

**Issue by tomhoag** [smartdevicelink/SmartDeviceLink-iOS#121]
Joel -- Thanks a bunch for the pointer to the [develop branch and the example project](https://github.com/smartdevicelink/SmartDeviceLink-iOS/issues/119).  Up and running w/o a problem.

Once I've established a connection with SDL what is the process for getting a UI to appear on screen?  In our meeting, Joey mentioned that there is a template to load and then populate?

Any pointers or high level instruction is appreciated!  Thanks again!

**Comment by joeljfischer** [comment]
There should be a default template on the screen. After sending the register request, you should be able to send a show request similarly, using `buildShowWith...` methods. This should allow you to get some text onto the screen.

**Comment by tomhoag** [comment]
Thanks Joel.  I'm assuming the default template is shown by clicking the 'i' button in SDL_core?   Is there supposed to be anything at the Home button or Settings button?

 I can now populate the fields using this bit of code:

```
SDLImage *sdlImage = [[SDLImage alloc] init];
sdlImage.value = @"right.png";
sdlImage.imageType = [SDLImageType DYNAMIC];
SDLShow *showRPC = [SDLRPCRequestFactory buildShowWithMainField1:@"mainField1"
                                                          mainField2:@"mainField2"
                                                          mainField3:@"mainField3"
                                                          mainField4:@"mainField4"
                                                           statusBar:@"statusBar"
                                                          mediaClock:@"mediaClock"
                                                          mediaTrack:@"mediaTrack"
                                                           alignment:[SDLTextAlignment CENTERED]
                                                             graphic:sdlImage
                                                         softButtons:nil //@[@"sb0",@"sb1",@"sb2",@"sb3",@"sb4"]
                                                       customPresets:@[@"cp0",@"cp1",@"cp2",@"cp3",@"cp4",@"cp5",@"cp6",@"cp7",@"cp9",@"cpA"]
                                                       correlationID:[self nextCorrelationID]];
    
[self.proxy sendRPCRequest:showRPC];
```

I had previously downloaded a couple images to SDL using this:

```
- (void)loadImages {
    
    [@[@"left.png",@"right.png"] enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
        
        UIImage *image =[UIImage imageNamed:obj];
        NSData *imageData = UIImagePNGRepresentation(image);
        
        NSInputStream *inputStream = [[NSInputStream alloc] initWithData:imageData];
        SDLPutFile *putFile = [SDLRPCRequestFactory buildPutFileWithFileName:obj
                                                                    fileType:[SDLFileType GRAPHIC_PNG]
                                                            persisistentFile:nil
                                                               correlationID:[self nextCorrelationID]];
        
        [self.proxy putFileStream:inputStream withRequest:putFile];
    }];
}
```

A couple follow-up questions:

What is the softButtons: array parameter expecting?  Where do these show up?

Using the code above, my image doesn't appear although there is "broken link" image.  I'm assuming that I've got the image size or file type wrong?  Currently, the image is a PNG 150x150.

Thanks!

![screenshot_3_17_15__1_08_pm](https://cloud.githubusercontent.com/assets/226088/6693019/acab5f12-cca6-11e4-91de-dff53095c607.png)

**Comment by joeljfischer** [comment]
> I'm assuming the default template is shown by clicking the 'i' button in SDL_core? Is there supposed to be anything at the Home button or Settings button?

Correct and no

> Using the code above, my image doesn't appear although there is "broken link" image. I'm assuming that I've got the image size or file type wrong? Currently, the image is a PNG 150x150.

Check to see if you get a putFile response of success, and make sure it's actually transferring correctly. I may need to double check, but I'm pretty sure there's some weird stuff going on with putFiles.

> What is the softButtons: array parameter expecting? Where do these show up?

These would show up on the right side, I believe. The array should be an array of SDLSoftButton instances. This will have to be a mutable array....I know.
