### ISSUE TITLE
Document SDLPrioritizedObjectCollection priority lower is 'higher'

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/SmartDeviceLink-iOS#143]
~~It should retrieve high priority objects first, but instead retrieves low priority objects first.~~

Because this is used with service numbers, lower numbers indicate higher priority. Since this semantically odd, it should be documented within the class.

**Comment by joeljfischer** [comment]
@hugh22 @Heath-FoMoCo Are lower numbers higher priority? Because that would mean this is functional then, just semantically weird.

**Comment by hugh22** [comment]
Nope, that looks like an error. The current spec (which I suspect will need changing) is to use the number of the service type as the priority with higher values going first.

**Comment by joeljfischer** [comment]
Okay, thanks, just wanted to make sure

**Comment by joeljfischer** [comment]
I plan to hold off fixing this until unit tests are merged so that I can test the fix properly.

**Comment by justinjdickow** [comment]
The current specification says, in section 4.

>Lower service numbers have higher priority and are sent ahead of higher service numbers.

I don't have an exact reference because I rewrote the [protocol spec for GitHub](https://github.com/smartdevicelink/protocol_spec#4-services) but my wording is

>Lower values for service type have higher delivery priority.

**Comment by joeljfischer** [comment]
@justinjdickow @hugh22 So...it's functional then? Just semantically odd? I can just change the test for high priority to be a lower number, and it should pass.

**Comment by justinjdickow** [comment]
@joeljfischer Assuming the service number is always used as the priority, it would seem it is functionally correct

**Comment by joeljfischer** [comment]
Alright, I'll alter the test then. This should be documented within the `SDLPrioritizedObjectCollection` class.

**Comment by joeljfischer** [comment]
Alright, I'll alter the test then. This should be documented within the `SDLPrioritizedObjectCollection` class.

**Comment by hugh22** [comment]
Yeah, that's right. It got turned around so that an RPC can pre-empt video streams.
