### ISSUE TITLE
HeaderDoc style documentation in files

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/SmartDeviceLink-iOS#15]
[Tutorial on HeaderDoc](http://www.raywenderlich.com/66395/documenting-in-xcode-with-headerdoc-tutorial)
[Jazzy](https://github.com/realm/jazzy)

We should document all of our methods next to the methods in header files. This will provide us with in Xcode documentation generation for alt-clicking on methods; as well as the opportunity to generate html based on the documentation.

**Comment by joeljfischer** [comment]
@Heath-FoMoCo @adein Can we get an update on this?

**Comment by Heath-FoMoCo** [comment]
Yes.  We are currently in the process of moving our 2.3.1 iOS proxy release into  a pull request from GIT Hub.  This will include most recent changes and our documentation.  Expectation is early next week.

**Comment by joeljfischer** [comment]
Awesome, thanks
