### ISSUE TITLE
Core supports voice recognition synonyms and tts name for app querying

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/SmartDeviceLink-iOS#180]
The languages array should be passed along in the onSystemRequest with the rest of the app query info. The full JSON is in the [server documentation](https://github.com/smartdevicelink/sdl_server/blob/master/docs/application_launching_v1.0.md#example-ios-response).

Core uses this information to support launching applications via voice recognition

```javascript
"languages": [
        "default": {
            "ttsName": "Awesome Music",
            "vrSynonyms": ["Awesome App", "Music Awesomeness"]
        },
        "EN-US": {
            "ttsName": "Awesome Music",
            "vrSynonyms": ["Awesome App", "Music Awesomeness"]
        }
        "ES-ES": {
            "ttsName": "música impresionante",
            "vrSynonyms": ["aplicación impresionante", "buena música"]
        }
      ]
```

**Comment by joeljfischer** [comment]
This will "just work" :tm: I don't parse each individual piece of the app, I just parse the url scheme and test it then pass it wholesale on to the completion block, which sends it to the server.
