### ISSUE TITLE
Does this SDK support video streaming?

### ISSUE THREAD

**Issue by akandul** [smartdevicelink/SmartDeviceLink-iOS#25]

**Comment by justinjdickow** [comment]
@adein Is video streaming available in the iOS SDK?

**Comment by adein** [comment]
It is in the AppLink Bitbucket repo, but it is still being tested.  Do we want to make it part of the upcoming iOS pull request, or wait until it's been tested and make a separate request?

**Comment by joeljfischer** [comment]
I don't want to delay the upcoming iOS pull request, so do that one first. The video streaming can go into a separate pull request, but you don't necessarily have to wait until it's tested. If it's modular enough to go into a separate feature branch, just do that and update the branch as fixes come in.

**Comment by joeljfischer** [comment]
See my PR here: https://github.com/smartdevicelink/SmartDeviceLink-iOS/pull/45 for how I'd like to structure larger feature PRs in the future.

**Comment by adein** [comment]
I don't think the changes are very drastic (I think it's just 1 added method in SDLProxy.m/h) and the code is already done, so it doesn't necessarily need a separate pull request for those reasons.

The only reason(s) to separate it is either:
a) to keep pull requests separated by topic/feature, or
b) wait until it's tested before issuing the request.

I'm ok with either way, I just want to align with whatever processes/guidelines are planned for or in place for the SDL repos.

**Comment by joeljfischer** [comment]
I think both a and b are solid reasons to separate them. Though regarding b, I'd prefer that the branch and PR be available before it's done testing, so that we can have a record of any updates that occur, and others can take a look easily.

**Comment by adein** [comment]
Ok, sounds good to me.

**Comment by akandul** [comment]
Thanks for update. Is AppLink Bitbucket repo public? Could you please provide link to this repo if it's public? When you plan to provide branch with video streaming here? Also could you please provide information about branch with video streaming when it will be created?

**Comment by adein** [comment]
The Bitbucket repo is Ford's internal private repo for the legacy AppLink/SDL code.  All SDL code is being moved into these public GitHub/GENIVI repos and future work will be done in these repos.  The video streaming pull request should be issued soon (after the "Documentation and misc updates") pull request is complete.
