### ISSUE TITLE
Vehicle Compatibility Matrix 

### ISSUE THREAD

**Issue by williamsjj** [smartdevicelink/SmartDeviceLink-iOS#28]
Is there a matrix showing features of SDL and what vehicles/models support which features (and over which transport)?

**Comment by joeljfischer** [comment]
@justinjdickow @Heath-FoMoCo

**Comment by justinjdickow** [comment]
There's not, Ford's market implementation supports all of the current features for approved applications. We plan on including this type of information on an SDL developer portal which consolidates the libraries, integration guides, and best practices, but also expect each adopting OEM to provide the necessary information and certification to their developers as well.
