### ISSUE TITLE
SmartDeviceLink.h references "SDLHmiZoneCapabilities.h" instead of "SDLHMIZoneCapabilities.h"

### ISSUE THREAD

**Issue by adein** [smartdevicelink/SmartDeviceLink-iOS#30]
Developer feedback: "The file is actually named FMCHMIZoneCapabilities.h (note the difference in casing), which causes the build to fail on case-sensitive file systems."

**Comment by joeljfischer** [comment]
I'm opening a hotfix pull request for this right now
