### ISSUE TITLE
Improper use of precompiled header

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/SmartDeviceLink-iOS#4]
The current precompiled header includes UIKit, which is not a framework needed to be imported and accessible in most classes in SDL so it should be removed.

The precompiled header already imports Foundation so Foundation imports can be removed elsewhere.

Anything that is imported in most classes should be moved to the precompiled header instead.

**Comment by joeljfischer** [comment]
Fixed in `develop`
