### ISSUE TITLE
Completion handlers are always called with "not completed" message in SDLProtocolMessageAssembler

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/SmartDeviceLink-iOS#92]
In `[SDLProtocolMessageAssembler handleMessage]`, the `completionHandler` is always called with `done` set to `NO` at the end of the function, even if the message assembly was completed.
```objc
if (self.parts.count == self.frameCount + 1) { // +1 since we also require the first-frame
    ...
    // Execute completion handler.
    if (completionHandler != nil) {
        completionHandler(YES, assembledMessage);
    }

    // Done with this data, release it.
    self.parts = nil;

}

// Not done, let caller know
if (completionHandler != nil) {
    completionHandler(NO, nil);
}
```
This results in the `completionHandler` being called twice when the message assembly is completed, once claiming that it was completed, and once claiming that it wasn't.

The last `if` statement should just be changed to an `else if` so that only one of the calls can be run.
```objc
if (self.parts.count == self.frameCount + 1) { // +1 since we also require the first-frame
    ...
    // Execute completion handler.
    if (completionHandler != nil) {
        completionHandler(YES, assembledMessage);
    }

    // Done with this data, release it.
    self.parts = nil;
}
// Not done, let caller know
else if (completionHandler != nil) {
    completionHandler(NO, nil);
}
```

**Comment by justinjdickow** [comment]
@jacobkeeler Probably a little nit picky but I think to be more clear about what is going on in this code it should actually read

```objc
// Not done, let caller know
else {
  if (completionHandler != nil) {
      completionHandler(NO, nil);
  }
}
```

because the if statement only determines if there is a completionHandler to call, and in the case that there were other operations to perform (not that there are), they should not be blocked by a nil completion handler
